## BiliBili视频

【【不要再看那些过时的PyTorch老教程了】2024巨献，PyTorch入门小白最新版全套教程(PyTorch入门/深度学习/神经网络/项目实战教程）】https://www.bilibili.com/video/BV1tH4y1c7Ud?p=7&vd_source=877d8021f1e4e120e907c47b8398eb6c

In [2]:
import numpy
!pip install  torch torchvision


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [3]:
import torch

a = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])


In [4]:
a = torch.Tensor(2,3,4)
print(a)
print(a.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [5]:
b = torch.ones(2,2)
print(b)
print(b.shape)

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [6]:
c = torch.eye(3,3)
print(c)
print(c.shape)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([3, 3])


In [7]:
d = torch.zeros_like(c)
print(d)
print(d.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [8]:
e = torch.ones_like(c)
print(e)
print(e.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])


In [9]:
f = torch.randn(2,3,4)
print(f)
print(f.shape)

tensor([[[-0.9028,  0.5348,  0.2289,  2.0100],
         [-0.6600, -0.4701,  0.3862,  0.6011],
         [ 0.4632, -0.1391,  0.6374, -0.8559]],

        [[-0.3868, -0.0595, -0.8155, -0.9603],
         [ 1.7459, -1.0963,  1.2972, -0.0252],
         [ 0.0673,  0.7326,  0.0569,  0.1308]]])
torch.Size([2, 3, 4])


In [10]:
# 高斯分布
g = torch.normal(mean=0.0,std=torch.rand(5))
print(g)
print(g.shape)

tensor([-0.3611, -0.6140, -0.5529,  0.0418,  0.3586])
torch.Size([5])


In [12]:
#均匀分布
h = torch.Tensor(2,2).uniform_(-3,1)
print(h)
print(h.shape)

tensor([[-2.0988, -1.4679],
        [ 0.4179,  0.4805]])
torch.Size([2, 2])


In [14]:
# 序列
i = torch.arange(0,10,2)
print(i)
print(i.shape)

tensor([0, 2, 4, 6, 8])
torch.Size([5])


In [16]:
# 等间隔序列
j = torch.linspace(2,10,3)
print(j)
print(j.shape)

tensor([ 2.,  6., 10.])
torch.Size([3])


In [17]:
#打乱索引
k = torch.randperm(10)
print(k)
print(k.shape)

tensor([2, 4, 6, 5, 3, 0, 1, 8, 9, 7])
torch.Size([10])


########################## numpy

In [19]:
import numpy as np
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l)
print(l.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
